"
Dolphin Smalltalk ODBC Database Connection Base (run time).
Copyright (c) Object Arts Ltd, 1997-2003. Portions copyright CGI Group (Europe) Ltd, 1997.

This package provides an interface to ODBC databases.

For documentation evaluate:
	SmalltalkSystem help: 'databaseconnectivity'
"
Class {
	#name : #ManifestDatabaseConnectionBase,
	#superclass : #PackageManifest,
	#category : #'ODBC-Core-Manifest'
}
